### ISSUE TITLE
udunits2 library is missing

### ISSUE THREAD

**Issue by GrgMdmn** [cedadev/cf-checker#106]
Hello,
I am writing you because I am wanting to check if my nc file is cf compliant, using the cf-checker tool. When using the test.sh file, all the outputs I get all contain the same error:
`FileNotFoundError: cfunits requires UNIDATA UDUNITS-2. Can't find the 'udunits2' library.`

I tried finding on the net if the udunits2 library exists for python but it seems that it does not.

Do you know how to fix this problem ?

Thanks in advance for answering.

**Comment by neumannd** [comment]
Hi @GrgMdmn ,

`cfunits` is the Python interface to the C-Library `udunits`/`udunits-2`. If you install `cfunits` via conda then the `udunits` package should bin installed alongside. If you install it differently, you might need to install it manually (or via the package repository of your operating system).

* the most recent release: https://downloads.unidata.ucar.edu/udunits/
* the GitHub Repo: https://github.com/Unidata/UDUNITS-2

**Comment by GrgMdmn** [comment]
Thanks alot, it works much better ! :)

**Comment by neumannd** [comment]
@GrgMdmn Happy to hear that. Probably, this issue can be closed?
