### ISSUE TITLE
Boundary value checks failing for scalar variables

### ISSUE THREAD

**Issue by piotrflorek** [cedadev/cf-checker#22]
Hi,
we were testing cfchecker with a file containing a scalar coordinate (soil level for mrsos), and it was failing on line 992 when trying to iterate over a 0-d numpy array.

An ugly quickfix might be something like

```python
for i, value in (enumerate(varData) if len(varData.shape) else enumerate([varData])):
```

**Comment by RosalynHatcher** [comment]
Implemented quick fix above.  Is planned to be re-written anyway with the major overhaul in the summer.
