### ISSUE TITLE
update conda package ...

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/cf-checker#23]
@agstephens 
i've seen you are in the process of updating the cf-checker conda package:
https://github.com/agstephens/cfchecker-feedstock

I've added the cfunits conda package:
https://github.com/conda-forge/cfunits-feedstock

... but i've taken the latest version cfunits=1.5.1.

There is also a cf_units package (used for example by the compliance-checker):
https://github.com/conda-forge/cf_units-feedstock

Probably cfunits and cf_units are doing the same thing ... but cf_units is also available for python 3.

**Comment by agstephens** [comment]
Hi @cehbrecht: Yes, unfortunately `cfunits` and `cf_units` are doing the same thing. One was developed to support `cfpython` and one to support `iris`. I am not aware of plans to merge them.

**Comment by agstephens** [comment]
Thanks @cehbrecht. I have updated the cfchecker to 3.0.5 and put in a pull request for the conda-forge feedstock: https://github.com/conda-forge/cfchecker-feedstock/pull/5 
Closing this issue now.
