### ISSUE TITLE
CF-1.7

### ISSUE THREAD

**Issue by github-MO** [cedadev/cf-checker#33]
Dears, when cross-checking a netcdf based on CF-1.7 convetion, the following error raises:
"ERROR (2.6.1): This netCDF file does not appear to contain CF Convention data."

It appears that the CFVersion class is not handling CF-1.7 (nor 1.8 which is currently drafted).

Could you please fix this issue?

**Comment by alaniwi** [comment]
The various other issues attached to this repo show that @RosalynHatcher is currently working on 1.7 support. I suggest we close this one unless she has anything to add?

**Comment by RosalynHatcher** [comment]
Yes, as Alan has said above, I am currently in the process of updating the CF Checker for CF-1.7

I will close this ticket now.  When the new version is ready I will advertise on the CF mailing list and tag a new release.

**Comment by github-MO** [comment]
thanks
