### ISSUE TITLE
CFChecker does not support adding a convention string in Coneventions attributes

### ISSUE THREAD

**Issue by senesis** [cedadev/cf-checker#40]
When provided with a file having such an attribute :
`        :Conventions = "CF-1.7 CMIP-6.2" ;
`
CFchecker complains :
```
=====================
Using CF Checker Version 3.0.5
Checking against CF Version CF-1.6
Using Standard Name Table Version 49 (2018-02-13T08:44:33Z)
Using Area Type Table Version 6 (22 February 2017)
ERROR: (2.6.1): This netCDF file does not appear to contain CF Convention data.
```
while the syntax used seems to comply with the CF convention for this attribute

**Comment by RosalynHatcher** [comment]
This has already been fixed in #28 and will be available at the next release scheduled soon.
