### ISSUE TITLE
using cdat-lite >= 6.0

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/cf-checker#5]
it looks like cf-checker can know be used with numpy >= 19 (skipped oldNumeric).

Can i use cdat-lite >= 6.0? Older versions worked only with numpy < 19.

The cdat-lite download is not available:

http://ndg.nerc.ac.uk/dist/cdat_lite-6.0rc2.tar.gz
https://pypi.python.org/pypi/cdat-lite

**Comment by agstephens** [comment]
Hi,

Yes, there was a problem with our server. It seems to have been fixed now.

Please try again, the package should now download from Pypi.

Thanks,

Ag

**Comment by cehbrecht** [comment]
Hi Ag,

i just tried the download link but it's not working ...

http://ndg.nerc.ac.uk/dist/cdat_lite-6.0rc2.tar.gz

When i install from pypi i get only the 5.x version.

Cheers,
Carsten

**Comment by RosalynHatcher** [comment]
CF Checker from version 3.0.0 no longer requires CDAT.  Closing Issue now.
