### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by giumas** [cedadev/cf-checker#51]
Any plan to support Windows? 

The `cfunits-python` dependency may make it a bit difficult (It only supports [MacOS and Linux](https://bitbucket.org/cfpython/cfunits-python/src/f83d785f9a0165ff80312d091b817947a3baaad2/setup.py#lines-86)).

**Comment by RosalynHatcher** [comment]
Sorry but there is currently no plan to support Windows.  The same is true for cf-units & cf-python.
