### ISSUE TITLE
wrong result when using auxillary coordinate with _Fillvalue

### ISSUE THREAD

**Issue by bertulus** [cedadev/cf-checker#52]
The cfchecker gives a Information (_Fillvalue used in a non standard way) when a auxiliary coordinate has a _FillValue attribute. The current CF-conventions explicitly allow this.

**Comment by RosalynHatcher** [comment]
Thank you for reporting this.  I will update the checker at the earliest opportunity.

Note to self:   This change applies from CF-1.6 onwards.
