### ISSUE TITLE
Update pip and conda channels

### ISSUE THREAD

**Issue by ashao** [cedadev/cf-checker#53]
The default release of cf-checker installed either through pip (https://pypi.org/project/cfchecker/) or via conda (https://anaconda.org/conda-forge/cfchecker) both default to the 3.0.5. release. At the CCCma we will be installing it by cloning this GitHub repo, however at your convenience could you please update the channels.

**Comment by RosalynHatcher** [comment]
PyPI and conda-forge have now been updated with the latest cfchecker release v3.1.1

**Comment by ashao** [comment]
Much appreciated @RosalynHatcher
