### ISSUE TITLE
Problem installing and running version 3.1.1

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/cf-checker#64]
Hi Ros, I struggled to get version 3.1.1 running, but eventually got it going: the problem was that `pip` automatically updates `cfunits` to the latest version, `3.X`, and this version of `cfunits` only works with python3, while the checker requires python2. I think the declaration for the checkers dependency on cfunits needs to be modified from `1.8 or later` to `1.8 to 1.9.1`.

**Comment by RosalynHatcher** [comment]
Hi Martin, Ah yes, sorry about that.  Someone else alerted me to that a couple of weeks ago and I've not quite got around to updating that declaration. 

I will attempt to do so this afternoon, otherwise on my return next week.
Thanks.

**Comment by RosalynHatcher** [comment]
Fixed in commit:  https://github.com/cedadev/cf-checker/commit/098fbbad24090ec4a1f8db62bacf2485904fd703
