### ISSUE TITLE
UnboundLocalError raised when running CF-checker via browser 

### ISSUE THREAD

**Issue by tsherwen** [cedadev/cf-checker#76]
When testing a COARDS compliant NetCDF4 file ([downloadable here](https://webfiles.york.ac.uk/WACL/SHERWEN_TOMAS/TEMP/Misc/PREFIA_York_GEOSChem_2x2.5_CEDS_20171231_v0.1.0.nc)), an UnboundLocalError is raised. The was raised whilst using the online browser version of cf-checker ([linked]( https://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl?cfversion=1.3)). 

The final section of error message pasted below and the full output linked too ([linked here](https://drive.google.com/file/d/1B5MGMgrXFlcruFoU1eCPyV1Eg0SLxvZ5/view?usp=sharing)). 

I have tested this fine with a script I normally use ([linked](https://github.com/geoschem/geos-chem/blob/master/NcdfUtil/perl/isCoards)), which raises no notable issues ([output linked here](https://drive.google.com/file/d/1f1iiHhhQUm0mL_SBDsK3Gb1YTAOyuUGF/view?usp=sharing
)). 

"
...

> ------------------
> Checking variable: EmisACET_Total
> ------------------
> 
> ------------------
> Checking variable: DryDep_SOAS
> ------------------
> Traceback (most recent call last):
>   File "/home/ros/anaconda2/bin/cfchecks", line 10, in
>     sys.exit(main())
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfchecker/cfchecks.py", line 3021, in main
>     inst.checker(file)
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfchecker/cfchecks.py", line 488, in checker
>     return self._checker()
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfchecker/cfchecks.py", line 728, in _checker
>     self.chkUnits(var,allCoordVars)
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfchecker/cfchecks.py", line 2251, in chkUnits
>     varUnit = Units(units)
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfunits/units.py", line 728, in __init__
>     units = _bytes_to_str(units)
>   File "/home/ros/anaconda2/lib/python2.7/site-packages/cfunits/units.py", line 27, in _bytes_to_str
>     return str(as_string)
> UnboundLocalError: local variable 'as_string' referenced before assignment

"

**Comment by RosalynHatcher** [comment]
Note to self: This should be fixed when online checker upgrade soon.

**Comment by RosalynHatcher** [comment]
Confirm checker no longer crashes with this file.
