### ISSUE TITLE
TypeError raised when running CF-checker in python3 environment

### ISSUE THREAD

**Issue by tsherwen** [cedadev/cf-checker#77]
The below TypeError is raised when running CF-checker in locally installed python3 environment. The listed dependencies are present ([full list of conda environment modules](https://drive.google.com/file/d/1Q0ZuSMPGEAW_8n8OcKJX_8MtKp2j6BP2/view?usp=sharing)).

The file being run is the same as in issue #76, with the terminal command below. 

    cfchecks <name of NetCDF file>

The latest master branch cf-checker was successfully installed with no issues (via `python setup.py install`).

"

> Traceback (most recent call last):
>   File "/users/ts551/scratch/conda_local/envs/py_3_7_master/bin/cfchecks", line 11, in <module>
>     load_entry_point('cfchecker==3.1.3', 'console_scripts', 'cfchecks')()
>   File "/users/ts551/scratch/conda_local/envs/py_3_7_master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/users/ts551/scratch/conda_local/envs/py_3_7_master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/users/ts551/scratch/conda_local/envs/py_3_7_master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/users/ts551/scratch/conda_local/envs/py_3_7_master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/mnt/lustre/users/ts551/conda_local/envs/py_3_7_master/lib/python3.7/site-packages/cfchecker-3.1.3-py3.7.egg/cfchecker/cfchecks.py", line 140, in <module>
>     newest_version = max(cfVersions)
> TypeError: '>' not supported between instances of 'CFVersion' and 'CFVersion'

"

**Comment by RosalynHatcher** [comment]
@tsherwen CF Checker version 3.1.3 is not python3 compatible.  The first version that works with python3 is 4.0.0 which I released on 9th October.

It doesn't look to have made it onto conda yet which I'll need to look at, but is available for download from PyPI.

Regards,
Ros.

**Comment by tsherwen** [comment]
@RosalynHatcher thanks for the quick reply!

I've downloaded via pip it is working fine. 

To confirm I originally installed via option 3 in the README, via direct by cloning the github and using setup.py, and not by conda. 

Cheers, 

Tomas
