### ISSUE TITLE
Conda-forge recipe

### ISSUE THREAD

**Issue by vinisalazar** [cedadev/cf-checker#95]
Hi,

Thank you for providing this package. I believe it would greatly benefit from a conda distribution. If you agree, I could attempt to submit a [conda-forge](https://conda-forge.org/) recipe to achieve this. The recipe is automatically updated by the conda-forge infrastructure based on this repository/pip's releases, but it does require a maintainer. In that case, it would be nice for one of the package's developers to agree to serve as a recipe maintainer (rather than me as the recipe's author).

What do you think?

Best,
Vini

**Comment by RosalynHatcher** [comment]
Hi Vini,

Thanks for the offer. I looked to do this a little while ago but found there was already a conda-forge recipe there. I haven't tested the latest upload but it looks to still be on there: https://anaconda.org/conda-forge/cfchecker.  If there is a problem with it and does need a new recipe I'm grateful for the help and happy to serve as recipe maintainer.
Thanks.
Cheers,
Rosalyn

**Comment by vinisalazar** [comment]
Hi @RosalynHatcher,

thanks. That is great news. Apologies for my oversight, I was searching for `cf-checker` rather than `cfchecker` and I did not find it. I installed it with conda just now and it worked great.

Would you consider adding conda installation instructions in the README? I could submit a PR for that, if you wish.

Best,
Vini

**Comment by RosalynHatcher** [comment]
Hi @vinisalazar ,

Sorry for the confusion.  I'm not actually sure who wrote that recipe; it wasn't me.  Slight inconsistencies in the naming which I ought to fix at some point.  Yes please do go ahead and submit a PR to add the conda installation instructions.  Thanks for noticing that it is missing.

Cheers,
Ros.

**Comment by vinisalazar** [comment]
No worries. Thank you for the quick reply.

The [recipe's feedstock](https://github.com/conda-forge/cfchecker-feedstock) shows the maintainers at the bottom of the README, in case you want to work on that in the future. I'll be glad to help in any way I can.

Best,
Vini
